language: haskell

ghc:
    - 7.8

install:
    - cabal install hlint
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests && cabal build && cabal test && hlint src

notifications:
    email: false
